# Generated by Django 2.1.7 on 2019-03-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('context', models.CharField(blank=True, help_text='Call Context', max_length=300, null=True)),
                ('from_cc', models.CharField(blank=True, help_text='cc of caller', max_length=300, null=True)),
                ('from_phone', models.CharField(blank=True, help_text='phone of caller', max_length=300, null=True)),
                ('from_name', models.CharField(blank=True, help_text='name of caller', max_length=300, null=True)),
                ('call_type', models.CharField(blank=True, help_text='type_of_call', max_length=300, null=True)),
                ('call_status', models.CharField(blank=True, help_text='Status of Call', max_length=300, null=True)),
                ('call_leg_data', models.TextField(help_text='Data of Call Legs')),
                ('webhook_url', models.CharField(blank=True, help_text='Webhook Url', max_length=300, null=True)),
                ('callee_info_cc', models.CharField(blank=True, help_text='cc of callee', max_length=300, null=True)),
                ('callee_info_phone', models.CharField(blank=True, help_text='phone of callee', max_length=300, null=True)),
                ('recording_file_name', models.CharField(blank=True, help_text='Recording File Name', max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Webhook-Data for Call',
                'verbose_name_plural': 'Webhook-Data for Calls',
            },
        ),
    ]
