# Generated by Django 2.1.7 on 2019-03-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookdata',
            old_name='ended_at',
            new_name='endedAt',
        ),
        migrations.RenameField(
            model_name='webhookdata',
            old_name='call_leg_data',
            new_name='legs',
        ),
        migrations.RenameField(
            model_name='webhookdata',
            old_name='started_at',
            new_name='startedAt',
        ),
    ]
