# Generated by Django 2.1.7 on 2019-03-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20190314_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdata',
            name='legs',
            field=models.CharField(help_text='Data of Call Legs', max_length=1024, null=True),
        ),
    ]
